.TH "CALC" "" "July 2013" "" ""
.SH "NAME"
\fBcalc\fR
.P
Simple command line calculator
.SH Getting Started
.P
Install the module with: \fBnpm install calc \-g\fR
.SH Documentation
.P
To run a calculation you need to pass 2 numbers to the \fBcalc\fR command as arguments\.
.SS Example
.P
\fBcalc 10 10\fR
.SH Examples
.P
\fI(Coming soon)\fR
.SH Contributing
.P
In lieu of a formal styleguide, take care to maintain the existing coding style\. Add unit tests for any new or changed functionality\. Lint and test your code using Grunt \fIhttp://gruntjs\.com/\fR\|\.
.SH Release History
.P
\fI(Nothing yet)\fR
.SH License
.P
Copyright (c) 2013 Jonathan Fielding
.br
Licensed under the MIT license\.

